eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

security:
  oauth2:
    resource:
      token-info-uri: http://auth-server-v1.1:6005/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

spring:
  datasource:
    username: root
    password: Password123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-1.cfhxt0t9eszb.us-east-2.rds.amazonaws.com:3306/mydb?createDatabaseIfNotExist=true
    dialect: org.hibernate.dialect.MySQL5Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
debug: true
