eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:6005/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
