eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

security:
  oauth2:
    resource:
      token-info-uri: http://auth-server-v1.1:6005/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

spring:
  datasource:
    url: jdbc:mysql://db:3306/mydb?createDatabaseIfNotExist=true

